services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: |
      npm install
      npx puppeteer browsers install chromium
    startCommand: "npm start"
    branch: main
    autoDeploy: true
